version: "3"
services:
  web:
    build: .
    ports:
      - "5000:80"      
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "sqWkMD4k"
      ACCEPT_EULA: "Y"