version: "3"
services:
  web:
    build: .
    ports:
      - "5001:5001"      
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "5000:1433"
    environment:
      SA_PASSWORD: "sqWkMD4k"
      ACCEPT_EULA: "Y"