version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"      
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "sqWkMD4k"
      ACCEPT_EULA: "Y"